#TODO: fix this file up

language:
  - node_js

node_js:
  - 8

cache:
  directories:
    - $HOME/.npm
    - frontend/node_modules
    - backend/node_modules

services:
  - postgresql

before_install: dpkg --compare-versions `npm -v` ge 6.0 || npm i -g npm@latest
install:
  - cd frontend && npm ci
  - cd ../backend && npm ci

branches:
  only:
  - master

jobs:
  include:
    - stage: publish
      script:
        # - cd ../frontend
        # - find src -name '*.js' | xargs grep 'localhost' --files-with-matches | xargs sed --in-place 's|http://localhost:[0-9]*|http://api.trucktracker.net|'
        # - npm run build
        # backend
        - cd ../backend
        - export NODE_ENV="development"
        - export PGUSER="postgres"
        - export PGPASSWORD=""
        - psql -c "create database traffic_counter"
        - npx knex migrate:latest
        - npm run lint
        - npm test
